# Generated by Django 3.2.13 on 2022-12-22 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=256)),
                ('excerpt', models.TextField()),
                ('subtitle', models.TextField()),
                ('content', models.TextField()),
                ('source', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=128)),
                ('source_url', models.TextField()),
                ('source_pfp', models.TextField()),
                ('published', models.DateField()),
                ('full_article', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MembershipToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_token', models.CharField(max_length=64, unique=True)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('valid_until', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Article_Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.article')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.tag')),
            ],
        ),
    ]
