# Generated by Django 3.2.13 on 2022-12-26 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hashed_token', models.CharField(max_length=64, unique=True)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('valid_until', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=50)),
                ('pfp', models.CharField(max_length=512)),
                ('link', models.CharField(max_length=512)),
                ('scraping_link', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=256)),
                ('headline_img', models.CharField(max_length=512)),
                ('subtitle', models.TextField()),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('link', models.CharField(max_length=512)),
                ('published', models.DateField()),
                ('paywall', models.BooleanField()),
                ('img_is_video', models.BooleanField(default=False)),
                ('authors', models.ManyToManyField(to='newsapp.Author')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.source')),
                ('tags', models.ManyToManyField(to='newsapp.Tag')),
            ],
        ),
    ]
