# Generated by Django 4.1.5 on 2023-02-08 06:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='N/A', max_length=50)),
                ('display_title', models.CharField(default='N/A', max_length=50)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MemberPreference',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('display_in_feed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hashed_token', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('valid_until', models.DateTimeField()),
                ('last_visit', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='N/A', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingFeatures',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512, null=True)),
                ('visible', models.BooleanField(default=False)),
                ('submitted', models.DateField(default=django.utils.timezone.now)),
                ('votes', models.ManyToManyField(default=None, to='newsapp.membershiptoken')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=50)),
                ('pfp', models.CharField(default='static/images/default_source_20x20.png', max_length=512)),
                ('scraping_link', models.CharField(max_length=512)),
                ('active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsapp.category')),
            ],
        ),
        migrations.AddField(
            model_name='membershiptoken',
            name='preferences',
            field=models.ManyToManyField(default=None, through='newsapp.MemberPreference', to='newsapp.source'),
        ),
        migrations.AddField(
            model_name='memberpreference',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.membershiptoken'),
        ),
        migrations.AddField(
            model_name='memberpreference',
            name='sources',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.source'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=256)),
                ('headline_img', models.CharField(default='static/images/index.png', max_length=512)),
                ('subtitle', models.TextField()),
                ('link', models.CharField(max_length=512)),
                ('published', models.DateTimeField(blank=True)),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('authors', models.ManyToManyField(to='newsapp.author')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsapp.source')),
                ('tags', models.ManyToManyField(to='newsapp.tag')),
            ],
        ),
    ]
