# Generated by Django 4.1.4 on 2023-02-20 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpreference',
            name='sources',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='newsapp.source'),
        ),
    ]
