# Generated by Django 4.1.4 on 2022-12-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_alter_article_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershiptoken',
            options={'managed': False},
        ),
    ]
