# Generated by Django 4.1.4 on 2023-02-20 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_alter_memberpreference_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpreference',
            name='sources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsapp.source'),
        ),
    ]
