# Generated by Django 4.1.4 on 2023-04-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_source_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
