# Generated by Django 4.1.4 on 2022-12-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_alter_membershiptoken_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='headline_img',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
