# Generated by Django 4.1.4 on 2022-12-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_alter_article_headline_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(),
        ),
    ]
