# Generated by Django 4.1.4 on 2022-12-30 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_alter_article_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
