# Generated by Django 4.1.4 on 2022-12-30 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_article_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='added',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
