# Generated by Django 4.1.4 on 2023-01-03 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0008_alter_article_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershiptoken',
            options={},
        ),
    ]
