# Generated by Django 4.1.4 on 2023-01-03 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0009_alter_membershiptoken_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptoken',
            name='last_visit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
