# Generated by Django 4.1.4 on 2023-01-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0010_membershiptoken_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptoken',
            name='hashed_token',
            field=models.CharField(max_length=64),
        ),
    ]
