# Generated by Django 4.1.4 on 2023-01-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0011_alter_membershiptoken_hashed_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingFeatures',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512, null=True)),
                ('visible', models.BooleanField(default=False)),
                ('votes', models.ManyToManyField(to='newsapp.membershiptoken')),
            ],
        ),
    ]
