# Generated by Django 4.1.4 on 2023-01-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0012_upcomingfeatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingfeatures',
            name='votes',
            field=models.ManyToManyField(default=None, to='newsapp.membershiptoken'),
        ),
    ]
