# Generated by Django 4.1.4 on 2023-01-19 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0013_alter_upcomingfeatures_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingfeatures',
            name='submitted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
