# Generated by Django 4.1.4 on 2023-01-24 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0014_upcomingfeatures_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastScrape',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=256)),
                ('last_scrape', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='article',
            name='img_is_video',
        ),
        migrations.RemoveField(
            model_name='article',
            name='paywall',
        ),
        migrations.AddField(
            model_name='source',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateField(blank=True),
        ),
    ]
