# Generated by Django 4.1.4 on 2023-01-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0015_lastscrape_remove_article_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='link',
        ),
        migrations.AlterField(
            model_name='source',
            name='pfp',
            field=models.CharField(default='static/default_source.png', max_length=512),
        ),
    ]
