# Generated by Django 4.1.4 on 2023-01-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0016_remove_source_link_alter_source_pfp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastScrape',
        ),
    ]
