# Generated by Django 4.1.4 on 2023-01-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0018_alter_source_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='pfp',
            field=models.CharField(default='static/images/default_source_20x20.png', max_length=512),
        ),
    ]
