# Generated by Django 4.1.4 on 2023-01-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0020_category_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='headline_img',
            field=models.CharField(default='static/images/index.png', max_length=512),
        ),
    ]
