# Generated by Django 4.1.4 on 2023-01-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0021_alter_article_headline_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(blank=True),
        ),
    ]
