# Generated by Django 4.1.4 on 2023-01-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0023_tag_display_title_alter_tag_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='display_title',
        ),
        migrations.AddField(
            model_name='category',
            name='display_title',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
