# Generated by Django 4.1.4 on 2023-01-31 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0026_remove_article_category_source_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_in_feed', models.BooleanField(default=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newsapp.membershiptoken')),
                ('sources', models.ManyToManyField(blank=True, to='newsapp.source')),
            ],
        ),
    ]
