# Generated by Django 4.1.4 on 2023-01-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0028_remove_memberpreference_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpreference',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
