# Generated by Django 4.1.4 on 2023-01-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0029_alter_memberpreference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpreference',
            name='member',
            field=models.ManyToManyField(blank=True, to='newsapp.membershiptoken'),
        ),
        migrations.AlterField(
            model_name='memberpreference',
            name='sources',
            field=models.ManyToManyField(blank=True, to='newsapp.source'),
        ),
    ]
